services:
  docker-postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: market
      POSTGRES_USER: market_admin
      POSTGRES_PASSWORD: marketplace1579
    ports:
      - "15432:5432"
    restart: unless-stopped
