spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/market
    schema: marketplace
    username: market_admin
    password: marketplace1579
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.xml
    default-schema: ${spring.datasource.schema}
    liquibase-schema: utility